version: 2

# Source Freshness
# Default timing-
# No Freshness check if no date is available or infrequent updates

# loaded_at_field is standard "Update Date" or most recently updated date field

sources:
  - name: SNOWFLAKE_SAMPLE_DATA
    description: 'Source data taking from snowflake '
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF10TCL
    tables:
      - name: STORE_SALES
        description: 'Store sales data'
        freshness:
          warn_after: { count: 365, period: day }
          error_after: { count: 400, period: day }